### PR TITLE
Temporary PR for tests of pos_disable_payment_restaurant module

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by GabbasovDinar** [comment]
image

**Comment by GabbasovDinar** [comment]
@ilmir-k I won't fix the pos_access_right doggie because this module is an OCA module and uses the OCA rules for lints
image

**Comment by ilmir-k** [comment]
@GabbasovDinar now we can remove pos_access_right module from here

**Comment by GabbasovDinar** [comment]
@ilmir-k DONE

**Pull request merged**
