### PR TITLE
:arrow_up::one::two: pos_order_print_check

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
On Apps page for pos_order_print_check: "No module found! You should try other search criteria."

**Comment by GabbasovDinar** [comment]
@Ramil-Mukhametzyanov  screenshot-25192-582-1f9531-base runbot it-projects info-2018 12 04-19-40-53

**Comment by Ramil-Mukhametzyanov** [comment]
> @Ramil-Mukhametzyanov screenshot-25192-582-1f9531-base runbot it-projects info-2018 12 04-19-40-53

Odoo 10.0 is installed on the runbot.

**Comment by GabbasovDinar** [comment]
@Ramil-Mukhametzyanov 
image

**Review by Ramil-Mukhametzyanov — APPROVED** [review]

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
One order is lost if the printer is turned off while POS is open and then the Order button is pressed.

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
Lost orders are related to POSBox and printers.

**Review by yelizariev — CHANGES_REQUESTED** [review]
no price, no html description

**Comment by yelizariev** [comment]
pos_cashier_select doesn't pass CI tests

**Comment by GabbasovDinar** [comment]
@yelizariev but it's addons-dev branch. @ilmir-k will prepare a description later. The pos_cashier_select tests I fixed in pos-addons

**Review by yelizariev — APPROVED** [review]
code looks good

**Comment by yelizariev** [comment]
We'll publish it in pos-addons

**Comment by yelizariev** [comment]
https://github.com/itpp-labs/pos-addons/pull/1250

**Pull request closed without merging**
