### PR TITLE
[10.0][NEW] pos_multi_session_kitchen

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by gustavovalverde** [comment]
@GabbasovDinar and @yelizariev please write to me for the needed funding to complete this.

**Comment by ilmir-k** [comment]
@gustavovalverde it requires extra 500 usd. But any part of this amount would allow to speed up the development. Thanks

**Comment by GabbasovDinar** [comment]
@ilmir-k @yelizariev @gustavovalverde Who can check the functionality of the module? I need reviews to continue working

**Comment by gustavovalverde** [comment]
@GabbasovDinar I'll be taking this weekend to test as much as I can from this module.

@akevinieron @frankpenalo this is a very interesting module to test and contribute to.

**Pull request merged**
